apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: es-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: es-client
subjects:
- kind: ServiceAccount
  name: es-client