apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: es-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: es-data
subjects:
- kind: ServiceAccount
  name: es-data
  namespace: logging
